title: "Zhuoran Wang"
email: "youremail@example.com"
description: "This is my personal website."
baseurl: "" # 不要修改，除非你在子目录下托管站点
url: "http://yourwebsite.com" # 修改为你的实际网址
theme: minima

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
