title: "Zhuoran Wang"
email: "wang.zr0511@outlook.com"
description: "This is my personal website."
baseurl: "" # 不要修改，除非你在子目录下托管站点
url: "https://wang-zhuoran.github.io/" # 修改为你的实际网址
# theme: minima  # 注释掉主题配置以使用自定义布局

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag


footer: yes
footer_url: "https://github.com/wang-zhuoran"
footer_text: "Page design by Zhuoran Wang"



sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "https://wang-zhuoran.github.io/"
 - name: "Research"
   link: "research"
 - name: "Projects"
   link: "projects"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
#  - name: "Blog"
#    link: "blog"
